name: Docker CI
on:
  push:
    branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: Build and push jaimeandres/transyto:develop image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jaimeandres/transyto:develop
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/ingestor/Dockerfile
